### ISSUE TITLE
Limit on the number of active background requests was reached for this app version

### ISSUE THREAD

**Issue by FrEaKmAn** [michaelklishin/rabbitmq-java-client-gae-example#1]
Hi

I'm using this factory, but I'm getting an error after some times

```
Uncaught exception from servlet
java.lang.IllegalStateException: Limit on the number of active background requests was reached for this app version.
    at com.google.appengine.api.system.SystemServiceImpl.translateException(SystemServiceImpl.java:42)
    at com.google.appengine.api.system.SystemServiceImpl.startBackgroundRequest(SystemServiceImpl.java:28)
    at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory.newThread(ApiProxyImpl.java:1169)
    at com.google.appengine.api.ThreadManager.createBackgroundThread(ThreadManager.java:92)
    at play.modules.rabbitmq.GAEThreadFactory.newThread(GAEThreadFactory.java:16)
    at com.rabbitmq.client.impl.Environment.newThread(Environment.java:24)
    at com.rabbitmq.client.impl.Environment.newThread(Environment.java:32)
    at com.rabbitmq.client.impl.ChannelManager.scheduleShutdownProcessing(ChannelManager.java:120)
    at com.rabbitmq.client.impl.ChannelManager.handleSignal(ChannelManager.java:100)
    at com.rabbitmq.client.impl.AMQConnection.finishShutdown(AMQConnection.java:741)
    at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:714)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:567)
    at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1$1.run(ApiProxyImpl.java:1161)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1.run(ApiProxyImpl.java:1156)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:441)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

any ideas what could be wrong? should I manually shutdown threads somewhere?

**Comment by michaelklishin** [comment]
There may be a natural limit to how many threads an app can use on GAE. Java client 3.6.0 will additionally allow specifying custom executors for things like heartbeats.

In the meantime, look for ways to use fewer connections.
